/// @desc

event_inherited()


pattern = [
	[INTENTIONS.BUFF, 2, EFFECTS.STRENGTH],
	[INTENTIONS.ATTACK, 25],
	[INTENTIONS.DEBUFF, 2, EFFECTS.VULNERABLE],
	[INTENTIONS.ATTACK, 25]
]


initializeEnemy()